# Generated by Django 2.2.6 on 2022-05-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220518_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='created',
        ),
    ]
